# Generated by Django 2.2.6 on 2020-08-10 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_updated',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
