# Generated by Django 2.2.6 on 2020-08-14 00:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
