# Generated by Django 2.2.6 on 2020-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kimchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('manufactured_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
