# Generated by Django 2.2.6 on 2020-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimchis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimchi',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
