# Generated by Django 2.2.6 on 2020-08-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimchis', '0004_auto_20200808_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kimchi',
            old_name='tag',
            new_name='tags',
        ),
    ]
