# Generated by Django 2.2.6 on 2020-08-13 22:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimchis', '0005_auto_20200808_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimchi',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
